from __future__ import annotations

import json
import re
import time
import unicodedata
from datetime import datetime
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

ROOT = Path(__file__).resolve().parent
RESULTS_ROOT = ROOT / "results" / "nanoGPT"


class Evidence(BaseModel):
    title: str
    source: str
    excerpt: str
    relevance: float = 0.0


class Review(BaseModel):
    faithfulness: float
    relevance: float
    task_completion: float
    reproducibility: float
    overall: float
    decision: Literal["PASS", "FAIL"]
    feedback: list[str] = Field(default_factory=list)


class AgentLog(BaseModel):
    agent: str
    message: str
    timestamp: str


class ResearchState(BaseModel):
    topic: str
    plan: dict[str, Any] = Field(default_factory=dict)
    research_evidence: list[Evidence] = Field(default_factory=list)
    experiment_results: dict[str, Any] = Field(default_factory=dict)
    draft: str = ""
    review: Review | None = None
    status: str = "idle"
    active_agent: str = ""
    logs: list[AgentLog] = Field(default_factory=list)
    artifact_dir: str = ""
    pdf_path: str = ""

    def log(self, agent: str, message: str) -> None:
        self.logs.append(AgentLog(agent=agent, message=message, timestamp=datetime.now().strftime("%H:%M:%S")))


class Agent:
    name = "Agent"

    def run(self, state: ResearchState, demo: bool = True) -> ResearchState:
        raise NotImplementedError

    @staticmethod
    def pause(demo: bool) -> None:
        if demo:
            time.sleep(0.7)


class PlannerAgent(Agent):
    name = "Planner"

    def run(self, state: ResearchState, demo: bool = True) -> ResearchState:
        state.status, state.active_agent = "planning", self.name
        state.log(self.name, "Decomposing the topic into a testable research plan.")
        self.pause(demo)
        state.plan = {
            "hypothesis": f"A structured multi-agent workflow can produce a traceable paper about: {state.topic}.",
            "baseline": "Saved nanoGPT experiment artifact.",
            "method": "Plan, retrieve evidence, write an IMRAD draft, then review it with a rubric.",
            "datasets": ["shakespeare_char", "enwik8", "text8"],
            "metrics": ["best validation loss", "training time", "inference throughput", "review score"],
            "success_criteria": "A reproducible draft, evidence dossier, metrics table, and reviewer decision.",
        }
        state.log(self.name, "Plan created with hypothesis, method, datasets, metrics, and success criteria.")
        return state


class ResearcherAgent(Agent):
    name = "Researcher"

    def run(self, state: ResearchState, demo: bool = True) -> ResearchState:
        state.status, state.active_agent = "researching", self.name
        state.log(self.name, "Retrieving traceable evidence from the local research dossier.")
        self.pause(demo)
        state.research_evidence = [
            Evidence(title="Attention Is All You Need", source="Vaswani et al., NeurIPS 2017", excerpt="Multi-head attention provides multiple representation subspaces for sequence modeling.", relevance=.98),
            Evidence(title="Are Sixteen Heads Really Better than One?", source="Michel et al., NeurIPS 2019", excerpt="Many attention heads can be removed with limited quality degradation in some settings.", relevance=.94),
            Evidence(title="Analyzing Multi-Head Self-Attention", source="Voita and Titov, ACL 2019", excerpt="Attention heads can specialize and their importance is not uniformly distributed.", relevance=.93),
        ]
        artifact = latest_artifact()
        if artifact:
            state.artifact_dir = str(artifact)
            ideas = load_json(artifact / "ideas.json", [])
            if ideas:
                item = next((x for x in ideas if x.get("novel")), ideas[0])
                state.research_evidence.append(Evidence(title=item.get("Title", "Local experiment idea"), source="Local AI Scientist artifact", excerpt=item.get("Experiment", "Saved experiment context."), relevance=.90))
            state.log(self.name, f"Loaded {len(state.research_evidence)} evidence items and local experiment context.")
        return state


class WriterAgent(Agent):
    name = "Writer"

    def run(self, state: ResearchState, demo: bool = True) -> ResearchState:
        state.status, state.active_agent = "writing", self.name
        state.log(self.name, "Writing a topic-specific IMRAD draft.")
        self.pause(demo)
        evidence = "\n".join(f"- {x.title} ({x.source}): {x.excerpt}" for x in state.research_evidence)
        state.draft = f"# {state.topic}\n\n## Abstract\nThis paper was generated by a shared-state multi-agent workflow.\n\n## Introduction\n{state.plan.get('hypothesis', '')}\n\n## Method\n{state.plan.get('method', '')}\n\n## Research evidence\n{evidence}\n\n## Results\nThe dashboard loads reproducible nanoGPT metrics from the saved artifact.\n\n## Limitations\nThis demo uses a compact CPU smoke-test; longer GPU experiments are required for strong scientific claims.\n"
        state.log(self.name, "Draft created with Introduction, Method, Evidence, Results, and Limitations.")
        return state


class ReviewerAgent(Agent):
    name = "Reviewer"

    def run(self, state: ResearchState, demo: bool = True) -> ResearchState:
        state.status, state.active_agent = "reviewing", self.name
        state.log(self.name, "Scoring evidence coverage, relevance, completion, and reproducibility.")
        self.pause(demo)
        evidence = min(1.0, len(state.research_evidence) / 4)
        artifact = 1.0 if state.experiment_results else .65
        state.review = Review(faithfulness=round(evidence, 2), relevance=.95 if state.plan else .4, task_completion=.95 if state.draft else .3, reproducibility=artifact, overall=round((evidence + .95 + (.95 if state.draft else .3) + artifact) / 4, 2), decision="PASS" if state.draft else "FAIL", feedback=["Keep claims tied to saved metrics and citations.", "Run longer GPU experiments before claiming a quality or speed improvement."])
        state.status, state.active_agent = ("completed" if state.review.decision == "PASS" else "needs_revision"), ""
        state.log(self.name, f"Review complete: {state.review.decision} ({state.review.overall:.2f}).")
        return state


def latest_artifact() -> Path | None:
    if not RESULTS_ROOT.exists():
        return None
    folders = [p for p in RESULTS_ROOT.iterdir() if p.is_dir()]
    return sorted(folders, key=lambda p: p.name, reverse=True)[0] if folders else None


def load_json(path: Path, fallback: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return fallback


def load_demo_results(state: ResearchState) -> ResearchState:
    artifact = latest_artifact()
    if not artifact:
        state.log("System", "No saved nanoGPT artifact was found.")
        return state
    state.artifact_dir = str(artifact)
    state.experiment_results = {"artifact": artifact.name, "runs": {}, "datasets": ["shakespeare_char", "enwik8", "text8"]}
    for run in ("run_0", "run_1"):
        state.experiment_results["runs"][run] = load_json(artifact / run / "final_info.json", {})
    state.log("System", f"Loaded saved results from {artifact.name}.")
    return state


def run_workflow(topic: str, demo: bool = True) -> ResearchState:
    state = ResearchState(topic=topic)
    if demo:
        load_demo_results(state)
    for agent in (PlannerAgent(), ResearcherAgent(), WriterAgent(), ReviewerAgent()):
        agent.run(state, demo=demo)
    state.pdf_path = create_generated_pdf(state)
    state.log("System", "Generated a topic-specific PDF report for download.")
    return state


def create_generated_pdf(state: ResearchState) -> str:
    output = ROOT / "results" / "smart_research_lab"
    output.mkdir(parents=True, exist_ok=True)
    safe = re.sub(r"[^a-zA-Z0-9_-]+", "_", state.topic).strip("_")[:48] or "research_paper"
    path = output / f"{safe}.pdf"
    lines = [state.topic, "Smart Research Lab - Generated Research Paper", "", "ABSTRACT", "This paper was generated by a shared-state multi-agent workflow.", "", "1. INTRODUCTION", state.plan.get("hypothesis", ""), "", "2. METHOD", state.plan.get("method", ""), "", "3. RESEARCH EVIDENCE"]
    lines.extend(f"{x.title} - {x.source}: {x.excerpt}" for x in state.research_evidence)
    lines.extend(["", "4. RESULTS", "Results were loaded from the saved nanoGPT experiment artifact."])
    run = state.experiment_results.get("runs", {}).get("run_1", {})
    for dataset, values in run.items():
        metric = values.get("means", {}).get("best_val_loss_mean")
        if metric is not None:
            lines.append(f"{dataset}: best validation loss {metric:.4f}")
    if state.review:
        lines.extend(["", "5. REVIEW", f"Decision: {state.review.decision}; overall score: {state.review.overall:.2f}."])
    write_simple_pdf(path, lines)
    return str(path)


def write_simple_pdf(path: Path, lines: list[str]) -> None:
    try:
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

        font_path = Path("C:/Windows/Fonts/arial.ttf")
        font_name = "Helvetica"
        if font_path.exists():
            pdfmetrics.registerFont(TTFont("ArialUnicode", str(font_path)))
            font_name = "ArialUnicode"
        styles = getSampleStyleSheet()
        title = ParagraphStyle("ReportTitle", parent=styles["Title"], fontName=font_name, alignment=TA_CENTER, fontSize=18, leading=23, spaceAfter=12)
        heading = ParagraphStyle("ReportHeading", parent=styles["Heading2"], fontName=font_name, fontSize=13, leading=17, spaceBefore=10, spaceAfter=5)
        body = ParagraphStyle("ReportBody", parent=styles["BodyText"], fontName=font_name, fontSize=10, leading=14, spaceAfter=6)
        document = SimpleDocTemplate(str(path), pagesize=A4, rightMargin=20 * mm, leftMargin=20 * mm, topMargin=18 * mm, bottomMargin=18 * mm)
        story = []
        for index, line in enumerate(lines):
            safe_line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            if index == 0:
                story.append(Paragraph(safe_line, title))
            elif line and (line.isupper() or line[:2].isdigit()):
                story.append(Paragraph(safe_line, heading))
            elif line:
                story.append(Paragraph(safe_line, body))
            else:
                story.append(Spacer(1, 4))
        document.build(story)
        return
    except ImportError:
        pass
    normalized = [unicodedata.normalize("NFKD", line).encode("ascii", "ignore").decode("ascii") for line in lines]
    wrapped = []
    for line in normalized:
        while len(line) > 92:
            wrapped.append(line[:92])
            line = line[92:]
        wrapped.append(line)
    content = ["BT", "/F1 11 Tf", "50 760 Td"]
    for line in wrapped:
        escaped = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        content.extend([f"({escaped}) Tj", "0 -16 Td"])
    content.append("ET")
    stream = "\n".join(content).encode("ascii", "ignore")
    objects = [b"<< /Type /Catalog /Pages 2 0 R >>", b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>", b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream"]
    pdf, offsets = bytearray(b"%PDF-1.4\n"), []
    for index, obj in enumerate(objects, 1):
        offsets.append(len(pdf)); pdf.extend(f"{index} 0 obj\n".encode()); pdf.extend(obj); pdf.extend(b"\nendobj\n")
    xref = len(pdf); pdf.extend(f"xref\n0 {len(objects)+1}\n0000000000 65535 f \n".encode())
    for offset in offsets:
        pdf.extend(f"{offset:010d} 00000 n \n".encode())
    pdf.extend(f"trailer\n<< /Size {len(objects)+1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF".encode())
    path.write_bytes(pdf)
